[package]
name = "conduit-wasm"
version = "0.1.0"
authors = ["Jet Li <jing.i.qin@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
stdweb = "0.4.20"
web_logger = "0.2"
yew = "0.10.0"
#yew = {git = "https://github.com/yewstack/yew", branch = "master"}
yew-router = "0.7.0"
#yew-router = {git = "https://github.com/yewstack/yew_router", branch = "master"}