name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: cargo install cargo-web
    - name: Build and develop
      run: cargo web start -p conduit-wasm
    - name: Run tests
      run: cargo test --verbose
